version: '3.8'

services:
  migrate:
    image: migrate/migrate
    profiles: ["manual"]
    depends_on:
      - postgres
    entrypoint:
      - "migrate"
      - "-path"
      - "/migrations"
      - "-database"
      - "postgres://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME}?sslmode=disable"
    volumes:
      - ./infra/database/migrations:/migrations

  sqlc:
    image: sqlc/sqlc:1.27.0
    working_dir: /app
    volumes:
      - ./:/app
    command: ["generate"]
