CREATE TABLE IF NOT EXISTS assistants (
    id SMALLSERIAL PRIMARY KEY,
    name VARCHAR(63) NOT NULL,
    phone VARCHAR(15) NOT NULL,
    password VARCHAR(255),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    period SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);