// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: assistant.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAssistantByID = `-- name: DeleteAssistantByID :exec
DELETE FROM assistants
WHERE id = $1
`

func (q *Queries) DeleteAssistantByID(ctx context.Context, id int16) error {
	_, err := q.db.Exec(ctx, deleteAssistantByID, id)
	return err
}

const findActiveAssistants = `-- name: FindActiveAssistants :many
SELECT id, name, phone, password, active, period, created_at, updated_at, email FROM assistants
WHERE active = TRUE
ORDER BY period, name
`

func (q *Queries) FindActiveAssistants(ctx context.Context) ([]Assistant, error) {
	rows, err := q.db.Query(ctx, findActiveAssistants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Assistant
	for rows.Next() {
		var i Assistant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Password,
			&i.Active,
			&i.Period,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAssistantByID = `-- name: FindAssistantByID :one
SELECT id, name, phone, password, active, period, created_at, updated_at, email FROM assistants
WHERE id = $1
`

func (q *Queries) FindAssistantByID(ctx context.Context, id int16) (Assistant, error) {
	row := q.db.QueryRow(ctx, findAssistantByID, id)
	var i Assistant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Password,
		&i.Active,
		&i.Period,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const findAssistantByPhone = `-- name: FindAssistantByPhone :one
SELECT id, name, phone, password, active, period, created_at, updated_at, email FROM assistants
WHERE phone = $1
`

func (q *Queries) FindAssistantByPhone(ctx context.Context, phone string) (Assistant, error) {
	row := q.db.QueryRow(ctx, findAssistantByPhone, phone)
	var i Assistant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Password,
		&i.Active,
		&i.Period,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
	)
	return i, err
}

const insertAssistant = `-- name: InsertAssistant :one
INSERT INTO assistants (name, phone, password, period, email)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertAssistantParams struct {
	Name     string
	Phone    string
	Password pgtype.Text
	Period   int16
	Email    pgtype.Text
}

func (q *Queries) InsertAssistant(ctx context.Context, arg InsertAssistantParams) (int16, error) {
	row := q.db.QueryRow(ctx, insertAssistant,
		arg.Name,
		arg.Phone,
		arg.Password,
		arg.Period,
		arg.Email,
	)
	var id int16
	err := row.Scan(&id)
	return id, err
}

const setAssistantPassword = `-- name: SetAssistantPassword :exec
UPDATE assistants
SET password = $1, updated_at = $2
WHERE id = $3
`

type SetAssistantPasswordParams struct {
	Password  pgtype.Text
	UpdatedAt pgtype.Timestamp
	ID        int16
}

func (q *Queries) SetAssistantPassword(ctx context.Context, arg SetAssistantPasswordParams) error {
	_, err := q.db.Exec(ctx, setAssistantPassword, arg.Password, arg.UpdatedAt, arg.ID)
	return err
}
