// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: assistant.sql

package sqlc

import (
	"context"
)

const findAssistantByPhone = `-- name: FindAssistantByPhone :one
SELECT id, name, phone, password, active, period, created_at, updated_at FROM assistants
WHERE phone = $1
`

func (q *Queries) FindAssistantByPhone(ctx context.Context, phone string) (Assistant, error) {
	row := q.db.QueryRow(ctx, findAssistantByPhone, phone)
	var i Assistant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Password,
		&i.Active,
		&i.Period,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
