// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Assistant struct {
	ID        int16
	Name      string
	Phone     string
	Password  pgtype.Text
	Active    bool
	Period    int16
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}
